### ISSUE TITLE
Support custom reporters along with failOnError

### ISSUE THREAD

**Issue by sheelah** [ilyakam/gulp-pug-linter#48]
Opening this as a follow-up on a comment you left on a [blog post of mine](https://sheelahb.com/blog/how-to-set-up-pug-linting-with-gulp/).

As discussed in the post, I was using gulp-pug-linter in a project but wanted to be able to both trigger the task to exit upon any lint errors and to set up a custom reporter to get lint output like [puglint-stylelish](https://github.com/aranasoft/puglint-stylish).

I think something like the snippet you left would work well:
```js
gulp.task('pug-lint', () => (
  gulp
    .src('./**/*.pug')
    .pipe(pugLinter({ failOnError: true }))
    .pipe(pugLinter.reporter(pugLintStylish))
))
```

Thanks!

**Comment by ilyakam** [comment]
Hi Sheelah, thank you for opening this issue. Since the `failAfterError` flag needed to be added to the plugin itself, I ended up rewriting the whole thing from the ground up. Please take a look at the [`README`](https://github.com/ilyakam/gulp-pug-linter/blob/eb41b74410229b38ee1f9f209ed3fe13269047ea/README.md) in #49 and let me know if you agree with the new direction and API. Thanks!

**Comment by sheelah** [comment]
@ilyakam Nice! Looks good to me.  I also think defining what kind of output the default reporter  (`{ reporter : 'default' }`) provides in the README would be useful.
