### ISSUE TITLE
Warning: pug-lintrc not found; falling back to default

### ISSUE THREAD

**Issue by johndavemanuel** [ilyakam/gulp-pug-linter#61]
I have a .pug-lintrc file in the same directory of the gulpfile.js but it always not found

GULP TASK
```
gulp.task('lint', function () {
  return gulp.src('./src/*.pug')
    .pipe(pugLinter({ reporter: '.pug-lintrc', failAfterError: true }))
});
```

.pug-lintrc file

```
{
    "disallowAttributeConcatenation": true
}
```

**Comment by ilyakam** [comment]
Hi @johndavemanuel,

I think that you are confusing the configuration files with the reporter. To fix your immediate problem, please change the above task to:

```js
gulp.task('lint', function () {
  return gulp.src('./src/*.pug')
    .pipe(pugLinter({ reporter: 'default', failAfterError: true }));
});
```

This plugin is designed to automatically read the configuration file/settings. There is no need to specify it in the code. Please see [`README`§About](https://github.com/ilyakam/gulp-pug-linter#about) for more info on that note.

The `reporter` configuration gives you the freedom to define your own reporter. You can learn more by playing around with the example in [`README`§Custom Reporter](https://github.com/ilyakam/gulp-pug-linter#custom-reporter).

In my experience, issues like these can be fixed with better documentation. If after re-reading the `README` it's still not clear, then [please submit a pull request](https://github.com/ilyakam/gulp-pug-linter/pulls/new) with your suggestions how to improve it.

**Comment by johndavemanuel** [comment]
@ilyakam 

Thank you for your kind response. It is working properly now.
