### ISSUE TITLE
Unexpected token ) gulp-pug-linter/index.js:67 

### ISSUE THREAD

**Issue by sravani123** [ilyakam/gulp-pug-linter#62]
I have included gulp-pug-linter in my project and written a task for running the pug lint. It was running successfully in local , But while deploying in VM , I am building my dist folder using gulp serve that is where i am getting error . 

Please find the error message which i am getting ,

![image](https://user-images.githubusercontent.com/1635595/61303575-62f46f00-a805-11e9-9b5c-2d43506899f7.png)

The code i have written for pug lint is below, 

`gulp.task('lint:jade', () => (
    gulp
        .src(['**/*.jade', '!_data/**/*.jade'], {cwd: CONFIG.site})
        .pipe(pugLinter({failOnError: true}))
        .pipe(pugLinter({reporter: pugLintStylish}))`

**Comment by ilyakam** [comment]
Hi @sravani123, I might have an idea what the problem is. But first, what version of Node are you running on that VM? You can find out by running `node --version` on that machine.

**Comment by ilyakam** [comment]
Hi @sravani123, I was able to isolate the issue to the following ES2017 feature: [trailing commas in function syntax](https://node.green/#ES2017-features-trailing-commas-in-function-syntax). As you can see in the screenshot below, the error can be reproduced when using Node.js version 7.10.1. The moment you switch to version 8.0.0 or above, that issue goes away. Since you did not run into other issues with the JavaScript syntax, my assumption is that your VM is running either version 6.x or 7.x.

#### Screenshots:

##### Version `7.10.1`
<img width="645" alt="node-7-10-1" src="https://user-images.githubusercontent.com/183227/61507878-6706c500-a99c-11e9-8e79-38b6afad401a.png">

##### Version `8.0.0`
<img width="520" alt="node-8-0-0" src="https://user-images.githubusercontent.com/183227/61507890-7554e100-a99c-11e9-8ceb-cc7115493c58.png">

[Tested with `n`](https://github.com/tj/n)

**Comment by ilyakam** [comment]
Fixed in #64 
Published in [1.2.1](https://github.com/ilyakam/gulp-pug-linter/releases/tag/1.2.1)

---

@sravani123, please reopen this issue if the problem persists.

**Comment by sravani123** [comment]
@ilakam thank you very much for the quick help..it resolved after I upgrade the node version in VM.
